config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  post 'posts' => 'posts#create'
  get 'posts/new' => 'posts#new', as: :new_post
  get 'posts/:id' => 'posts#show', as: :post
  get 'posts/:id/edit' => 'posts#edit', as: :edit_post
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'

  get 'users' => 'users#index'
  post 'users' => 'users#create'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  post 'post/:id' => 'comments#create'
  delete 'comment/:id' => 'comments#destroy', as: :comment

  put 'dislike/post/:id' => 'posts#downvote', as: :dislike
  put 'like/post/:id' => 'posts#upvote', as: :like

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/about' => 'static_pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # resources :users do
  #   resources :posts
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true
  validates :industry, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize
    redirect_to login_path if current_user.nil?
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
    @post = Post.find(params[:id])
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post
    if @comment.save
      redirect_to post_path(@post)
    else
      flash[:notice] = "Write a message to post comment."
      redirect_to :back
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment Deleted"
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit([:body])

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    @post.user = current_user

    if @post.save
      redirect_to root_path
    else
      flash.now[:notice] = "Type Some Gossip, Gurl!"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    redirect_to @post if @post.user != current_user
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      flash[:notice] = "Post Updated"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post Deleted"
    redirect_to users_path
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    print params[:view]
    if params[:view] == ('index') && current_user
      redirect_to '/#' + @post.id.to_s
    elsif current_user
      redirect_to :back
    else
      flash[:notice] = "Login or Sign Up to vote!"
      redirect_to :back
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    if params[:view] == 'index' && current_user
      redirect_to '/#' + @post.id.to_s
    elsif current_user
      redirect_to :back
    else
      flash[:notice] = "Login or Sign Up to vote!"
      redirect_to :back
    end
  end

  private
  def post_params
    (params.require(:post).permit(:title, :boss_name, :boss_company, :boss_title, :body))
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      flash[:notice] = "Logged In!"
      redirect_to root_path
    else
      flash[:notice] = "Invalid Email/Password. Please Try Again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged Out!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    redirect_to login_path if !current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    if @user.save
      session[:user_id] = @user.id.to_s
      flash.now[:notice] = "Sign up successful!"
      redirect_to users_path
    else
      flash[:notice] = "Invalid Profile Credentials - Try Again."
      flash[:alert] = "Email/Username may already be in use."
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:notice] = "Profile Updated"
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @user.destroy
    flash.now[:notice] = "Profile Deleted"
    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:email, :user_name, :industry, :company, :title, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>

        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Gossip Hollywood Gurl</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'partials/nav' %>
        <div>
            <% if notice %>
            <div class="alert-success"><%= notice %></div>
            <% end %>
        </div>

        <div>
            <% if alert %>
          <div class="alert-danger">  <%= alert %></div>
            <% end %>
        </div>
      <div class="container"
        <%= yield %>
      </div>
    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" id="nav-bar-root-btn"><%= link_to 'Gossip Hollywood Gurl', root_path %></div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                    <% if current_user %>
                <li id="navbar-current-user">
                    <%= "Hello, #{current_user.user_name}" %>
                </li>
                <li>
                    <%= link_to "POST YOUR GOSSIP!", new_post_path %>
                </li>
                <li>
                    <%= link_to "Profile", users_path %>
                </li>
                <li>
                    <%= link_to "log Out", logout_path, method: :delete %>
                </li>
            <% else %>
                <li>
                    <%= link_to 'Log In', login_path %>
                </li>
                <li>
                    <%= link_to 'Sign Up', new_user_path %>
                </li>
                <% end %>
                <li>
                    <%= link_to "About", about_path %>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

    <div>
        <%= f.text_field :title, {class: "form-control", placeholder: "Story Title?"} %>
    </div>

    <div>
        <%= f.text_field :boss_name, {class: "form-control", placeholder: "Boss' name? - ex: asshole, Ari Gold, etc..."} %>
    </div>

    <div>
        <%= f.text_field :boss_company, {class: "form-control", placeholder: "Boss' company?"} %>
    </div>

    <div>
        <%= f.text_field :boss_title, {class: "form-control", placeholder: "Boss' title or position?"} %>
    </div>

    <div>
        <%= f.text_area :body, {class: "form-control", placeholder: "Story time!", size: "50x10"} %>
    </div>

    <%= f.submit "Post your stuff!", {class: "btn btn-primary"} %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>

<%= render 'form' %>

<%= link_to "Delete This Post", post_path, method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>

<%= link_to 'Back', root_path %>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <% @posts.each do |p| %>
            <div class="post-preview" id="<%= p.id %>">
                <ul>
                    <h2 class="post-title">
                        <%=link_to "#{p.title}", post_path(p) %>
                    </h2>
                    <h3 class="post-subtitle">
                        <%= p.body %>
                    </h3>
                </a>
                <p class="post-meta">Post by:
                    <%= p.user.user_name %>
                    <i><%= time_ago_in_words(p.created_at) %>
                        ago</i>
                        <span id="comments-counter">
                          <%=link_to "Comments: #{p.comments.size}", post_path(p), {class: "btn btn-link btn-xs"} %>
                        </span>
                </p>
                <span>
                    <%= link_to "LOL Welcome to Hollywood! #{p.get_upvotes.size}", like_path(p, {view: 'index'}), {class: "btn btn-info", method: :put} %>
                </span>
                <span>
                    <%= link_to "You should quit... #{p.get_downvotes.size}", dislike_path(p, {view: 'index'}), {class: "btn btn-warning", method: :put}  %>
                </span>


                <hr>
            </ul>
            <% end %>
        </div>
        <hr>
    </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container text-center">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading text-center">
                    <h2>Create some gossip! The jucier the better...</h2>
                    <br>
                    <h4>Only thing required is a Title and a Story.<br> Be as vague or as specific as you want!</h4>
                </div>
                <div class="text-center">
                <div class="panel-body">
                    <%= render 'form' %>
                </div>
                <div>
                  <%= link_to "Home Page", root_path %>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-preview">
                <ul>
                    <h2 class="post-title">
                        <%= @post.title %>
                    </h2>
                    <h3 class="post-subtitle">
                        <p>Boss:
                            <%= @post.boss_name %></p>
                        <p>Company:
                            <%= @post.boss_company %></p>
                        <p>Boss Title:
                            <%= @post.boss_title %></p>
                    </p>
                </h3>
                <h4><%= @post.body %></h4>
            </a>
            <p class="post-meta">Post by:
                  <%= @post.user.user_name %>
                <i><%= time_ago_in_words(@post.created_at) %>
                    ago</i>
            </p>
            <div>
                <!-- upvote -->
                <span>
                    <%= link_to "LOL Welcome to Hollywood! #{@post.get_upvotes.size}", like_path(@post, {view: 'Post.find(params[:id])'}), {class: "btn btn-info", method: :put} %>
                </span>
                <!-- Downvote -->
                <span>
                    <%= link_to "You should quit... #{@post.get_downvotes.size}", dislike_path(@post, {view: 'Post.find(params[:id])'}), {class: "btn btn-warning", method: :put}  %>
                </span>
            </div>
            <hr>
        </ul>
    </div>
    <hr>
    <h4>
        <strong>Comments</strong>
    </h4>
    <div>
        <ul>
            <% @post.comments.each do |comment| %>
            <div>
                <h5>Comment by:
                    <%= comment.user.user_name %>
                    <i><%= time_ago_in_words(comment.created_at) %>
                        ago</i>
                </h5>
                <%= comment.body %>
            </div>
            <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete your comment?"} if current_user == comment.user%>
            <hr>
            <% end %>
        </ul>
    </div>
    <!-- new comment div -->
    <p>New Comment:</p>
    <div id="new-comment-container">
        <%= form_for @comment, url:{controller: "comments", action: "create"} do |f| %>
        <% if current_user %>
        <%= f.text_area :body, placeholder: "Type Here...", size: "50x4" %>
        <div>
        <%= f.submit "Post Comment", {class: "btn btn-primary"} %>
      </div>
    <% else %>
        <%= f.text_area :body, disabled: true, placeholder: "Login/sign-up to comment!"  %>
        <% end %>
        <% end %>
    </div>
</div>
</div>
</div>

app/views/static_pages/about.html.erb
<div id="about">
<h1>Welcome to Gossip Hollywood Gurl!</h1>

<p>Here we have only one thing we want to share, and that is all the shitty things our bosses make us do in the entertainment industry. Post gossip, comment on other gossip, and give sound advice. Have fun! #GHG</p>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :email, {class: "form-control", placeholder: "*Email"} %>
  </div>
  <div>
    <%= f.text_field :user_name, {class: "form-control", placeholder: "*Username"} %>
  </div>
  <div>
    <%= f.text_field :industry, {class: "form-control", placeholder: "*Industry"} %>
  </div>
  <div>
    <%= f.text_field :company, {class: "form-control", placeholder: "Company"} %>
  </div>
  <div>
    <%= f.text_field :title, {class: "form-control", placeholder: "Job title"} %>
  </div>
  <div>
    <%= f.password_field :password, {class: "form-control", placeholder: "*password"} %>
  </div>
  <div>
    <%= f.password_field :password_confirmation, {class: "form-control", placeholder: "*password confirmation"} %>
  </div>
  <div>
    <%= f.submit "Create Account", {class: "btn btn-primary"} %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :user_name %>
    <%= f.text_field :user_name %>
  </div>
  <div>
    <%= f.label :industry %>
    <%= f.text_field :industry %>
  </div>
  <div>
    <%= f.label :company %>
    <%= f.text_field :company %>
  </div>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :new_password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :new_password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>

<%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure you want to delete your account?"} %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-xs-6">
      <h1>Your info</h1>
        <p>Email:
            <%= @user.email %></p>
        <p>Username:
            <%= @user.user_name %></p>
        <p>Industry:
            <%= "#{@user.industry}" if @user.industry %></p>
        <p>Company:
            <%= "#{@user.company}" if @user.company %></p>
        <p>Job Title:
            <%= "#{@user.title}" if @user.title %></p>
        <p><%= link_to "Edit Your Account Info", edit_user_path(current_user) %></p>
    </div>
    <div class="col-xs-6">
      <h1>Your posts</h1>
            <% @user.posts.each do |post| %>
            <hr>
            <h4><%= post.title %></h4>
            <%= post.body %>
            <br>
            <%= link_to "Edit Your Post", edit_post_path(post) %>
            <% end %>
            <hr>
    </div>
</div>

app/views/users/new.html.erb
<div class="container text-center">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Sign up!</h2>
                    <br>
                    <h5>* denotes required field</h5>
                    <h6>Profile info is not public information, except your username. That way you won't get fired ;)<h6></div>
                        <div class="panel-body">
                            <%= render 'form' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>